apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: action-api
  description: Shows list of API used in retailer-notification-preference
spec:
  type: openapi
  lifecycle: production
  owner: messaging-team
  system: messaging-portal
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.1
      title: Action API
      license:
        name: MIT
    servers:
      - url: https://ws.narvar.com
    paths:
      /api/v1/event/:
        post:
          summary: Action API Endpoint
          description: Pass the Payload to hit action endpoint
          produces:
          - "application/json"
          parameters:
          - in: "body"
            name: "body"
            description: "Updating the RNP preferences"
            required: true
          responses:
            "400":
              description: "Bad Request"
            "404":
              description: "Not Found"
