apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Bala-backstage5
  description: Backstage-Testing5
  annotations:
    jira/project-key: MSG
    backstage.io/techdocs-ref: url:https://github.com/narvar/carrier-data-ingestion/tree/PRD-197
    narvar-wiki/url: https://narvar.atlassian.net/wiki/spaces/PDT/pages/427885314/BCC+Scrape+Implementation+Instructions
    narvar-speca/url: AA, BB, CC
    narvar-datadog/url:
      - https://www.gmail.com
      - https://www.google.com
    narvar-noflake/url: B
    narvar-grafana/url: C
  tags:
    - java
    - python
spec:
  type: service
  lifecycle: experimental
  owner: bala
  providesApis:
    - messaging-api
