apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: beas-api
  description: Shows list of API used in beas
spec:
  type: openapi
  lifecycle: production
  owner: partnership
  system: Demandware-Cartridge
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.1
      title: Raavi
      license:
        name: MIT
    servers:
      - url: https://beas.narvar.com/api/v1
    paths:
      /magento/handshake:
        post:
          summary: Posting an order for beas
          description: Passing Order detail
          produces:
          - "application/json"
          parameters:
          - in: "body"
            name: "body"
            description: "passing the payload"
            required: true
          - name: x-magento-retailer
            in: header
            description: x-magento-retailer
            required: true
            type: string
          - name: x-magento-hmac-sha256
            in: header
            description: x-magento-hmac-sha256
            required: true
            type: string
          - name: x-magento-store
            in: header
            description: x-magento-store
            required: true
            type: string
          responses:
            "200":
              description: "successful operation"


      /magento/integration/callback:
        post:
          summary: Posting an order for beas
          description: Passing Order detail
          produces:
          - "application/json"
          parameters:
          - in: "body"
            name: "body"
            description: "passing the payload"
            required: true
          - name: x-magento-retailer
            in: header
            description: x-magento-retailer
            required: true
            type: string
          - name: oAuth2
            in: header
            description: oAuth2
            required: true
            type: string
          - name: x-magento-store
            in: header
            description: x-magento-store
            required: true
            type: string
          responses:
            "200":
              description: "successful operation"
              
      /magento/integration/login:
        post:
          summary: Posting an order for beas
          description: Passing Order detail
          produces:
          - "application/json"
          parameters:
          - in: "body"
            name: "body"
            description: "passing the payload"
            required: true
          - name: x-magento-retailer
            in: header
            description: x-magento-retailer
            required: true
            type: string
          - name: oAuth2
            in: header
            description: oAuth2
            required: true
            type: string
          - name: x-magento-store
            in: header
            description: x-magento-store
            required: true
            type: string
          responses:
            "200":
              description: "successful operation"
              
      /magento/integration/endpoints:
        post:
          summary: Posting an order for beas
          description: Passing Order detail
          produces:
          - "application/json"
          parameters:
          - in: "body"
            name: "body"
            description: "passing the payload"
            required: true
          - name: x-magento-retailer
            in: header
            description: x-magento-retailer
            required: true
            type: string
          - name: oAuth2
            in: header
            description: oAuth2
            required: true
            type: string
          - name: x-magento-store
            in: header
            description: x-magento-store
            required: true
            type: string
          responses:
            "200":
              description: "successful operation"
