apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: customer-notification-preferences-api-test
  description: Shows list of API used in retailer-notification-preference
spec:
  type: openapi
  lifecycle: production
  owner: messaging-team
  system: messaging-portal
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.1
      title: Retailer Notification Preference
      license:
        name: MIT
    servers:
      - url: http://internal-consumer-notify-prefs-prod01-256782917.us-west-2.elb.amazonaws.com
    paths:
      /api/v1/notify-preferences/customer-level/customer/{customerId}:
        get:
          summary: Getting customer level optin details
          description: Passing customer Id as path parameter
          produces:
          - "application/json"
          parameters:
          - name: "customerId"
            in: "path"
            description: Passing Customer Id to get Customer Level optin details
            required: true
            type: "string"
          responses:
            "200":
              description: "successful operation"
