apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: customer-notification-preferences-api-test
  description: Shows list of API used in retailer-notification-preference
spec:
  type: openapi
  lifecycle: production
  owner: messaging-team
  system: messaging-portal
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.1
      title: Retailer Notification Preference
      license:
        name: MIT
    servers:
      - url: http://internal-consumer-notify-prefs-prod01-256782917.us-west-2.elb.amazonaws.com
    paths:
      /api/v1/notify-preferences/customer-level/customer/{customerId}:
        get:
          summary: Getting customer level optin details
          description: Passing customer Id as path parameter
          produces:
          - "application/json"
          parameters:
          - name: "customerId"
            in: "path"
            description: Passing Customer Id to get Customer Level optin details
            required: true
            type: "string"
          responses:
            "200":
              description: "successful operation"
      /api/v1/notify-preferences/order-level/customer/{customerID}/order/{orderId}:        
        post:
          summary: CNP Optin Order Level
          description: Creating CNP optin for Order level
          consumes:
          - "application/json"
          produces:
          - "application/json"
          parameters:
          - name: "customerId"
            in: "path"
            description: "Passing customer Id to the path parameter"
            required: true
            type: "string"
          - name: "orderId"
            in: "path"
            description: "Passing order Id to the path parameter"
            required: true
            type: "string"
          - in: "body"
            name: "body"
            description: "Creating the CNP Optin"
            required: true
          responses:
            "400":
              description: "Bad Request"
            "404":
              description: "Not Found"
      /api/v1/notify-preferences/order-level/customer/{customerId}?order_id={orderId}:        
        get:
          summary: CNP Optin Order Level
          description: Creating CNP optin for Order level
          consumes:
          - "application/json"
          produces:
          - "application/json"
          parameters:
          - name: "customerId"
            in: "path"
            description: "Passing customer Id to the path parameter"
            required: true
            type: "string"
          - name: "orderId"
            in: "query"
            description: "Passing order Id to the path parameter"
            required: true
            type: "string"
          responses:
            "400":
              description: "Bad Request"
            "404":
              description: "Not Found"

