apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: raavi
  description: Shows list of API used in raavi
spec:
  type: openapi
  lifecycle: production
  owner: partnership
  system: Demandware-Cartridge
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.1
      title: Raavi
      license:
        name: MIT
    servers:
      - url: http://internal-acf47a1a-prod01-retailerno-f376-1880905605.us-west-2.elb.amazonaws.com
    paths:
      /retailer-preferences/retailer/{retailerName}:
        get:
          summary: Getting Latest retailer Notification preferenecs
          description: Passing the Retailer name to get the RNP updates
          produces:
          - "application/json"
          parameters:
          - name: "retailerName"
            in: "path"
            description: "Passing retailer name to get the RNP preferences"
            required: true
            type: "string"
          - name: Access-Control-Allow-Origin
            in: header
            description: access-contorl-origin
            required: true
            type: string
          - name: Access-Control-Allow-Methods
            in: header
            description: access-contorl-methods
            required: true
            type: string
          responses:
            "200":
              description: "successful operation"
